### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by foxlee25** [faradaj/BlurBehind#5]
Hi there ,
 This is cool work  and i  just copy blur and blurBehind 2 class is work well  but  i got this issue when i test it  .

 java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
Caused by: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@432c02b8
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1170)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:745)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:602)
       at com.xxx.utils.v.doInBackground(BlurBehind.java:71)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)

------ 
 look like cause by bitmap recycle .Do you have any idea ? Thanks .

**Comment by faradaj** [comment]
Hi @foxlee25 ,
I wouldn't expect this exception.
Are you sure you are using the latest version?
